### ISSUE TITLE
Attempt to create a Machines from CommunityGalleries fails with HTTP status 500

### ISSUE THREAD

**Issue by MrBatschner** [gardener/machine-controller-manager-provider-azure#108]
**What happened**:

Attempting to create VMs on Azure from the following `machineClass`:

```
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: my-machine-class
credentialsSecretRef:
  name: cloudprovider
  namespace: --REDACTED--
nodeTemplate:
  capacity:
    cpu: "2"
    gpu: "0"
    memory: 7Gi
  instanceType: Standard_DS2_v2
  region: northeurope
  zone: no-zone
provider: Azure
providerSpec:
  location: northeurope
  properties:
    hardwareProfile:
      vmSize: Standard_DS2_v2
    machineSet:
      id: --REDACTED--
      kind: availabilityset
    osProfile:
      adminUsername: --REDACTED--
      linuxConfiguration:
        disablePasswordAuthentication: true
        ssh:
          publicKeys:
            keyData: --REDACTED--
            path: --REDACTED--
    storageProfile:
      imageReference:
        communityGalleryImageID: /CommunityGalleries/gardenlinux-13e998fe-534d-4b0a-8a27-f16a73aef620/Images/gardenlinux/Versions/1283.0.0
      osDisk:
        caching: None
        createOption: FromImage
        diskSizeGB: 35
        managedDisk:
          storageAccountType: Standard_LRS
  resourceGroup: --REDACTED--
  subnetInfo:
    subnetName: --REDACTED--
    vnetName: --REDACTED--
  tags:
    Name: --REDACTED--
    kubernetes.io-cluster-shoot--it--tmxra-py1: "1"
    kubernetes.io-role-node: "1"
    kubernetes.io_arch: amd64
    networking.gardener.cloud_node-local-dns-enabled: "true"
    node.kubernetes.io_role: node
    worker.garden.sapcloud.io_group: worker-1
    worker.gardener.cloud_cri-name: containerd
    worker.gardener.cloud_pool: worker-1
    worker.gardener.cloud_system-components: "true"
secretRef:
  name: --REDACTED--
  namespace: --REDACTED--
```

Note `communityGalleryImageID: /CommunityGalleries/gardenlinux-13e998fe-534d-4b0a-8a27-f16a73aef620/Images/gardenlinux/Versions/1283.0.0` in the StorageProfile.

From MCMs logs:

```
I1005 16:12:20.859358       1 core.go:91] Machine creation request has been processed for "shoot--myproject--myworkernode"
E1005 16:12:20.859383       1 machine.go:359] Error while creating machine shoot--myproject--myworkernode: machine codes error: code = [Internal] message = [compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=500 -- Original Error: Code="InternalOperationError" Message="An internal error occurred in the operation."]
```

**What you expected to happen**:

Machines from CommunityGalleryImages will get created, Azure should not return a 500 status code.

**How to reproduce it (as minimally and precisely as possible)**:

Try to create a machine from the above posted machineClass.
