### ISSUE TITLE
machine-controller-manager cannot delete Machine when the resource group is already deleted

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/machine-controller-manager-provider-azure#19]
**What happened**:

```
$ k -n shoot--foo--bar get machines shoot--foo--bar-bar-z3-5bf676f44d-kt27p -o yaml
```

```yaml
status:
  currentStatus:
    lastUpdateTime: "2020-11-20T07:52:09Z"
    phase: Terminating
  lastOperation:
    description: 'Cloud provider message - compute.VirtualMachinesClient#List: Failure
      responding to request: StatusCode=404 -- Original Error: autorest/azure: Service
      returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource
      group ''shoot--foo--bar'' could not be found."'
    lastUpdateTime: "2020-11-20T07:52:09Z"
    state: Failed
    type: Delete
```

**What you expected to happen**:
machine-controller-manager should be able to delete Machine when the resource group is already deleted. For example the azure cloud-controller-manager can handle this case and can delete Service of type LoadBalancer when the underlying resource-group is already deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an Azure Machine
2. Delete the underlying resource group
3. Ensure that machine-controller-manager cannot delete the Machine CR

**Anything else we need to know**:

**Environment**:
- machine-controller-manager version: v0.34.3
